### ISSUE TITLE
Error when deserializing various types when the data contains `Option.none()`

### ISSUE THREAD

**Issue by zsolt-donca** [javaslang/javaslang-jackson#64]
There is an error when deserializing JSON containing nulls to various collection types with `Option` as type argument. The collection types include `Seq` and its subtypes, `Set` types, `Either`, and `Tuple`. `Map` and `Multimap` is apparently not affected, when using `Option` the value type*. 

Concrete example: deserializing `[null, "foo"]` into `List<Option<String>>` should produce `List(Option.none(), Option.some("foo"))`, but instead, it throws the below exception. When the data does not contain `null`, deserialization is fine.

The error is:
```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of VALUE_NULL token
 at [Source: ["1",null,null]; line: 1, column: 5]

	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:857)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at javaslang.jackson.datatype.deserialize.OptionDeserializer.deserialize(OptionDeserializer.java:45)
	at javaslang.jackson.datatype.deserialize.OptionDeserializer.deserialize(OptionDeserializer.java:28)
	at javaslang.jackson.datatype.deserialize.TupleDeserializer.deserialize(TupleDeserializer.java:49)
	at javaslang.jackson.datatype.deserialize.TupleDeserializer.deserialize(TupleDeserializer.java:30)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2745)
...
```

I also have a fix for this issue: #65.

\* Note that since maps are converted to JSON objects, their keys cannot be `null` or `Option.none`, as `null` cannot be a property of a JSON object. The keys cannot be any non-primitive type either; otherwise serializing them just makes the keys `toString`'d, and deserialization fails.

**Comment by danieldietrich** [comment]
Thank you @zsolt-donca. Ruslan is currently on vacation, he will check it when he's back.

**Comment by ruslansennov** [comment]
Hi @zsolt-donca 
Thank you for your contribution
