### ISSUE TITLE
Javaslang container types don't work with polymorphic types

### ISSUE THREAD

**Issue by v1ctor** [javaslang/javaslang-jackson#66]
Hi! 

I figured out that javaslang jackson module don't know how to work with polymorphic types inside containers.
For example Jdk8Module work  fine with polymorphic types.
Here are tests to reproduce this behaviour:

```java
public class Test {

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
    @JsonSubTypes({
            @JsonSubTypes.Type(value = A.class, name = "a"),
            @JsonSubTypes.Type(value = B.class, name = "b"),
    })
    public interface I {}

    public static class A implements I {
        private final int a;

        @JsonCreator
        public A(@JsonProperty("a") int a) {
            this.a = a;
        }

        public int getA() {
            return a;
        }
    }

    public static class B implements I {
        private final int b;

        @JsonCreator
        public B(@JsonProperty("b") int b) {
            this.b = b;
        }

        public int getB() {
            return b;
        }
    }

    @Test
    public void deserializeOptionalA() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new Jdk8Module());

        Optional<I> i = mapper.readerFor(new TypeReference<Optional<I>>(){}).readValue("{\"type\":\"a\", \"a\":1}");
        Assert.assertTrue(i.isPresent());
        Assert.assertTrue(i.get() instanceof A);
        Assert.assertEquals(((A)i.get()).getA(), 1);
    }

    @Test
    public void deserializeOptionalB() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new Jdk8Module());

        Optional<I> i = mapper.readerFor(new TypeReference<Optional<I>>(){}).readValue("{\"type\":\"b\", \"b\":1}");
        Assert.assertTrue(i.isPresent());
        Assert.assertTrue(i.get() instanceof B);
        Assert.assertEquals(((B)i.get()).getB(), 1);
    }

    @Test
    //FAILED
    public void deserializeOptionA() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JavaslangModule());

        Option<I> i = mapper.readerFor(new TypeReference<Option<I>>(){}).readValue("{\"type\":\"a\", \"a\":1}");
        Assert.assertTrue(i.isDefined());
        Assert.assertTrue(i.get() instanceof A);
        Assert.assertEquals(((A)i.get()).getA(), 1);
    }

    @Test
    //FAIlED
    public void deserializeOptionB() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JavaslangModule());

        Option<I> i = mapper.readerFor(new TypeReference<Option<I>>(){}).readValue("{\"type\":\"b\", \"b\":1}");
        Assert.assertTrue(i.isDefined());
        Assert.assertTrue(i.get() instanceof B);
        Assert.assertEquals(((B)i.get()).getB(), 1);
    }
}
```

In two last tests I get this:

```java
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.mapkeen.DeserializationTest$I: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: {"type":"b", "b":1}; line: 1, column: 1]

	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1420)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1011)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:149)
	at javaslang.jackson.datatype.deserialize.OptionDeserializer.deserialize(OptionDeserializer.java:35)
	at javaslang.jackson.datatype.deserialize.OptionDeserializer.deserialize(OptionDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1622)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1217)
	at com.mapkeen.DeserializationTest.deserializeOptionB(DeserializationTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by v1ctor** [comment]
Found the similar problem in Guava module https://github.com/FasterXML/jackson-datatype-guava/issues/42 maybe can help.

**Comment by v1ctor** [comment]
It seems like you don't use TypeDeserializer at all. I don't understand where is better place to integrate it.  
For me it's not really clear why you take deserializers from context implementing ResolvableDeserializer instead of taking them from DeserializationConfig like it is made here https://github.com/FasterXML/jackson-datatype-jdk8/blob/2.6/src/main/java/com/fasterxml/jackson/datatype/jdk8/Jdk8Deserializers.java

**Comment by v1ctor** [comment]
There is the same problem with serialization. But I haven't found solution yet.

**Comment by danieldietrich** [comment]
Hi, @ruslansennov will take a look after his holiday.

**Comment by ruslansennov** [comment]
> For me it's not really clear why you take deserializers from context implementing ResolvableDeserializer instead of taking them from DeserializationConfig

I'll investigate this, thanks
