### ISSUE TITLE
XML deserialization bug 

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang-jackson#87]
This code
```java
@Test
public void testXmlSerialization() throws IOException {
    String javaUtilValue = xmlMapper().writeValueAsString(new XmlSerializeJavaslang());
    Assert.assertEquals(xmlMapper().writeValueAsString(new XmlSerializeJavaUtil()), javaUtilValue);
    XmlSerializeJavaslang restored = xmlMapper().readValue(javaUtilValue, XmlSerializeJavaslang.class);
    Assert.assertEquals(restored.transitTypes.size(), 3);  
}
```
fails with
```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.Integer out of FIELD_NAME token
 at [Source: java.io.StringReader@140e5a13; line: 1, column: 51] (through reference chain: javaslang.jackson.datatype.seq.XmlSerializeJavaslang["transitTypes"])

	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:857)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:460)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:309)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:287)
	at javaslang.jackson.datatype.deserialize.ArrayDeserializer.deserialize(ArrayDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
	at javaslang.jackson.datatype.seq.ListTest.testXmlSerialization(ListTest.java:127)
```

**Comment by emmanueltouzery** [comment]
looking a little at this... jackson-dataformat-xml has a WrapperHandlingDeserializer.

There it's used to wrap a normal deserializer, or not =>
https://github.com/FasterXML/jackson-dataformat-xml/blob/2.6/src/main/java/com/fasterxml/jackson/dataformat/xml/deser/XmlBeanDeserializerModifier.java#L81

**Comment by emmanueltouzery** [comment]
I have no idea whether that's really the issue we have, but if the deserializer doesn't inherit from [beandeserializerbase](https://github.com/FasterXML/jackson-databind/blob/2.6/src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializerBase.java) that code just bails out, and we don't inherit from that (and I guess it's not easy to change because we use type parameters and that one forces `Object`).

If we get to the end of that function, the last line is `return new WrapperHandlingDeserializer(deser);` which looks very interesting...

I'll stop looking for now as I know way too little on that... I hope I helped you a little maybe.

**Comment by emmanueltouzery** [comment]
(btw I did not debug just looked at the code, so maybe this code is not even run, just guessing here, don't take my babblings too seriously)
